name: whatsapp_call
description: A Whatsapp call application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  bouncing_widget: ^2.0.0
#  flutter_contacts: ^1.0.0
  fluttercontactpicker: ^4.6.0
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.18
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.3
  get: ^4.6.1
  cloud_firestore: ^3.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/splash.png
  android: true

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
