name: whatsapp_call
description: A Whatsapp call application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  bouncing_widget: ^2.0.0
  flutter_contacts: ^1.1.2
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
